//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POT.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string branchAddress {
            get {
                return ResourceManager.GetString("branchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string branchNbr {
            get {
                return ResourceManager.GetString("branchNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE.
        /// </summary>
        internal static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company info.
        /// </summary>
        internal static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER NBR..
        /// </summary>
        internal static string CUSTOMERNBR {
            get {
                return ResourceManager.GetString("CUSTOMERNBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date made.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateSignature {
            get {
                return ResourceManager.GetString("DateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete DB user.
        /// </summary>
        internal static string DeleteDBUser {
            get {
                return ResourceManager.GetString("DeleteDBUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY.
        /// </summary>
        internal static string DELIVERY {
            get {
                return ResourceManager.GetString("DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string DeliveryMain {
            get {
                return ResourceManager.GetString("DeliveryMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document nbr..
        /// </summary>
        internal static string DocumentNbr {
            get {
                return ResourceManager.GetString("DocumentNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit region.
        /// </summary>
        internal static string EditRegion {
            get {
                return ResourceManager.GetString("EditRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADE.
        /// </summary>
        internal static string Made {
            get {
                return ResourceManager.GetString("Made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by.
        /// </summary>
        internal static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE.
        /// </summary>
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACK.
        /// </summary>
        internal static string PACK {
            get {
                return ResourceManager.GetString("PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTLIST.
        /// </summary>
        internal static string PARTLIST {
            get {
                return ResourceManager.GetString("PARTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUA.
        /// </summary>
        internal static string QUA {
            get {
                return ResourceManager.GetString("QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIPT.
        /// </summary>
        internal static string RECEIPT {
            get {
                return ResourceManager.GetString("RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        internal static string ReceiptMain {
            get {
                return ResourceManager.GetString("ReceiptMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionID.
        /// </summary>
        internal static string RegionID {
            get {
                return ResourceManager.GetString("RegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select main region.
        /// </summary>
        internal static string SelectMainRegion {
            get {
                return ResourceManager.GetString("SelectMainRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIAL NBR.
        /// </summary>
        internal static string SERIALNBR {
            get {
                return ResourceManager.GetString("SERIALNBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DB user.
        /// </summary>
        internal static string SetDBUser {
            get {
                return ResourceManager.GetString("SetDBUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT.
        /// </summary>
        internal static string SWIFT {
            get {
                return ResourceManager.GetString("SWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date print.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
    }
}
